spring.application.name=distributed-task-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/task_engine
spring.datasource.username=postgres
spring.datasource.password=TaskEngine@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus


server.port=8091

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=60s

spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.shutdown.await-termination-period=60s